package main

// Single import of the shared renderer core. Every public `core` symbol is
// re-exported into `main` so the CLI's importers, GPU output adapter, and
// scene builders use the SAME renderer (CPU + Metal GPU) as the Houdini
// plugin. The renderer lives in one place: core/.
import lc "./core"

AABB :: lc.AABB
AxisAlignedBoundingBox :: lc.AxisAlignedBoundingBox
BVH_Node :: lc.BVH_Node
Camera :: lc.Camera
Color :: lc.Color
Environment :: lc.Environment
FlattenedScene :: lc.FlattenedScene
GICachePoint :: lc.GICachePoint
GLASS_DELTA_ROUGHNESS :: lc.GLASS_DELTA_ROUGHNESS
GPUCylinderLight :: lc.GPUCylinderLight
GPUDiscLight :: lc.GPUDiscLight
GPULightTriangle :: lc.GPULightTriangle
GPUMaterial :: lc.GPUMaterial
GPUPunctualLight :: lc.GPUPunctualLight
GPUQuadLight :: lc.GPUQuadLight
GPUSceneData :: lc.GPUSceneData
GPUSphere :: lc.GPUSphere
GPUSphereLight :: lc.GPUSphereLight
GPU_Frame :: lc.GPU_Frame
Hit_Record :: lc.Hit_Record
INV_PI :: lc.INV_PI
INV_PI_F64 :: lc.INV_PI_F64
Light :: lc.Light
Light_Kind :: lc.Light_Kind
Light_Sample :: lc.Light_Sample
Lumbre_Core :: lc.Lumbre_Core
MAX_SPHERES :: lc.MAX_SPHERES
Material :: lc.Material
Material_Kind :: lc.Material_Kind
Mesh :: lc.Mesh
OIDN_API :: lc.OIDN_API
OIDN_DEVICE_TYPE_CPU :: lc.OIDN_DEVICE_TYPE_CPU
OIDN_Set_Shared_Filter_Image :: lc.OIDN_Set_Shared_Filter_Image
PI_F64 :: lc.PI_F64
Photon :: lc.Photon
Point3 :: lc.Point3
ROOT_NODE_INDEX :: lc.ROOT_NODE_INDEX
Ray :: lc.Ray
Render_Buffer :: lc.Render_Buffer
Render_Config :: lc.Render_Config
Render_GPU_Buffers :: lc.Render_GPU_Buffers
Render_Work :: lc.Render_Work
Rng :: lc.Rng
Scene :: lc.Scene
SceneNode :: lc.SceneNode
Sphere :: lc.Sphere
TWO_PI :: lc.TWO_PI
TextureMap :: lc.TextureMap
Triangle :: lc.Triangle
Vec3 :: lc.Vec3
aabb_hit :: lc.aabb_hit
aniso_alphas :: lc.aniso_alphas
at :: lc.at
auto_gather_radius :: lc.auto_gather_radius
build_bvh :: lc.build_bvh
build_default_scene_graph :: lc.build_default_scene_graph
build_env_distribution :: lc.build_env_distribution
build_icosphere :: lc.build_icosphere
build_sphere_scene_graph :: lc.build_sphere_scene_graph
build_triangle_bvh :: lc.build_triangle_bvh
bvh_node_capacity :: lc.bvh_node_capacity
clearcoat_alpha_sq :: lc.clearcoat_alpha_sq
clone_texture :: lc.clone_texture
compute_world_transforms :: lc.compute_world_transforms
cylinder_light_pdf :: lc.cylinder_light_pdf
debug_print_lights :: lc.debug_print_lights
degrees_to_radians :: lc.degrees_to_radians
destroy_environment :: lc.destroy_environment
destroy_flattened_scene :: lc.destroy_flattened_scene
destroy_gpu_frame :: lc.destroy_gpu_frame
destroy_material_textures :: lc.destroy_material_textures
destroy_render_buffer :: lc.destroy_render_buffer
destroy_scene :: lc.destroy_scene
destroy_texture :: lc.destroy_texture
dielectric_f0 :: lc.dielectric_f0
disc_light_pdf :: lc.disc_light_pdf
env_lookup :: lc.env_lookup
env_luminance :: lc.env_luminance
env_pdf :: lc.env_pdf
env_sample :: lc.env_sample
flatten_scene_graph :: lc.flatten_scene_graph
get_ray :: lc.get_ray
ggx_D :: lc.ggx_D
ggx_D_aniso :: lc.ggx_D_aniso
ggx_G :: lc.ggx_G
ggx_G1 :: lc.ggx_G1
ggx_G1_aniso :: lc.ggx_G1_aniso
ggx_G_aniso :: lc.ggx_G_aniso
ggx_alpha_sq :: lc.ggx_alpha_sq
ggx_lambda_aniso :: lc.ggx_lambda_aniso
ggx_pdf :: lc.ggx_pdf
gpu_render_frame :: lc.gpu_render_frame
hit_bvh :: lc.hit_bvh
hit_scene :: lc.hit_scene
hit_sphere :: lc.hit_sphere
hit_triangle :: lc.hit_triangle
hit_triangle_bvh :: lc.hit_triangle_bvh
is_absolute_path :: lc.is_absolute_path
is_nee_light :: lc.is_nee_light
length_squared :: lc.length_squared
light_pdf :: lc.light_pdf
linear_to_srgb :: lc.linear_to_srgb
load_environment :: lc.load_environment
load_texture :: lc.load_texture
load_texture_from_memory :: lc.load_texture_from_memory
lumbre_core_init :: lc.lumbre_core_init
lumbre_core_render_cpu :: lc.lumbre_core_render_cpu
lumbre_core_render_gpu :: lc.lumbre_core_render_gpu
lumbre_core_replace_triangles :: lc.lumbre_core_replace_triangles
luminance_color :: lc.luminance_color
m_ceil :: lc.m_ceil
m_floor :: lc.m_floor
make_area_light :: lc.make_area_light
make_camera :: lc.make_camera
make_checker_texture :: lc.make_checker_texture
make_cylinder_light :: lc.make_cylinder_light
make_disc_light :: lc.make_disc_light
make_distant_light :: lc.make_distant_light
make_node :: lc.make_node
make_point_light :: lc.make_point_light
make_sphere_light :: lc.make_sphere_light
make_spot_light :: lc.make_spot_light
make_tangent_vec :: lc.make_tangent_vec
make_texture :: lc.make_texture
material_is_lambertian_like :: lc.material_is_lambertian_like
material_needs_uv :: lc.material_needs_uv
near_zero :: lc.near_zero
normalize_material :: lc.normalize_material
oidn_denoise :: lc.oidn_denoise
oidn_error :: lc.oidn_error
oidn_load :: lc.oidn_load
oidn_load_symbol :: lc.oidn_load_symbol
pow5 :: lc.pow5
power_heuristic :: lc.power_heuristic
principled_eval_f :: lc.principled_eval_f
principled_evaluate :: lc.principled_evaluate
principled_f0 :: lc.principled_f0
principled_f90 :: lc.principled_f90
principled_lobe_weights :: lc.principled_lobe_weights
principled_pdf :: lc.principled_pdf
principled_pdf_simple :: lc.principled_pdf_simple
principled_sample :: lc.principled_sample
principled_sample_glass :: lc.principled_sample_glass
principled_specular_dg :: lc.principled_specular_dg
quad_light_pdf :: lc.quad_light_pdf
ray_color :: lc.ray_color
reflect :: lc.reflect
reflect_half :: lc.reflect_half
reflect_over :: lc.reflect_over
reflectance :: lc.reflectance
refract :: lc.refract
render_cpu_to_buffer :: lc.render_cpu_to_buffer
render_gpu_to_buffer :: lc.render_gpu_to_buffer
render_worker :: lc.render_worker
rng_f64 :: lc.rng_f64
rng_f64_range :: lc.rng_f64_range
rng_in_unit_disk :: lc.rng_in_unit_disk
rng_in_unit_sphere :: lc.rng_in_unit_sphere
rng_next :: lc.rng_next
rng_unit_vector :: lc.rng_unit_vector
rng_vec3_range :: lc.rng_vec3_range
rotate_y :: lc.rotate_y
sample_cylinder_light :: lc.sample_cylinder_light
sample_disc_light :: lc.sample_disc_light
sample_distant_light :: lc.sample_distant_light
sample_ggx_microfacet :: lc.sample_ggx_microfacet
sample_ggx_ndf :: lc.sample_ggx_ndf
sample_ggx_reflection :: lc.sample_ggx_reflection
sample_ggx_reflection_aniso :: lc.sample_ggx_reflection_aniso
sample_ggx_vndf :: lc.sample_ggx_vndf
sample_ggx_vndf_aniso :: lc.sample_ggx_vndf_aniso
sample_light :: lc.sample_light
sample_point_light :: lc.sample_point_light
sample_quad_light :: lc.sample_quad_light
sample_sphere_light :: lc.sample_sphere_light
sample_spot_light :: lc.sample_spot_light
sample_texture_bilinear :: lc.sample_texture_bilinear
scatter :: lc.scatter
schlick_fresnel :: lc.schlick_fresnel
schlick_scalar :: lc.schlick_scalar
set_face_normal :: lc.set_face_normal
sphere_aabb :: lc.sphere_aabb
sphere_light_pdf :: lc.sphere_light_pdf
srgb_to_linear :: lc.srgb_to_linear
subsurface_random_walk_cpu :: lc.subsurface_random_walk_cpu
surface_tangent :: lc.surface_tangent
surrounding_box :: lc.surrounding_box
total_light_count :: lc.total_light_count
transform_dir :: lc.transform_dir
transform_normal_dir :: lc.transform_normal_dir
transform_point :: lc.transform_point
transform_triangle :: lc.transform_triangle
triangle_aabb :: lc.triangle_aabb
triangle_centroid :: lc.triangle_centroid
write_color :: lc.write_color
